receivers:
  otlp:
    protocols:
      grpc:
  hostmetrics:
    collection_intervals: 10s
    scrapers:
      memory:
      network:
processors:
  batch:
    timeout: 10s
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
